Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python310/assignment2.0.py

STRING OPERATIONS

THE ORIGINAL STRING IS: "PYTHON IS A CASE SENSITIVE LANGUAGE"
	LENGTH OF THE GIVEN STRING: 35
	STRING IN REVERSED ORDER IS:"EGAUGNAL EVITISNES ESAC A SI NOHTYP"
	NEW STRING:"A CASE SENSITIVE"
	STRING AFTER THE CHANGES:"PYTHON IS A CASE SENSITIVE LANGUAGE"
	INDEX OF "a" IN THE GIVEN STRING : -1
	STRING AFER REMOVING THE WHITE SPACES:"PYTHONISACASESENSITIVELANGUAGE"

STRING FORMATTING

ENTER YOUR NAME:VAIBHAV GUPTA
ENTER YOUR SID:21104073
ENTER THE NAME OF YOUR DEPARTMENT:Electrical
ENTER YOUR CGPA:9.9

Hey VAIBHAV GUPTA here!!       
MY SID is 21104073       
I am from Electrical Branch and my CGPA is 9.9.

BITWISE OPERATORS

a: 56
b: 10

a&b: 8
a|b: 58
a^b: 50
LEFT SHIFTING BOTH a and b BY 2 BITS: a-224,b-40
RIGHT SHIFTING a BY 2 AND b BY 4 BITS: a-14,b-0

GREATEST NUMBER CALCULATOR

ENTER YOUR FIRST NUMBER:15
ENTER YOUR SECOND NUMBER:12
ENTER YOUR THIRD NUMBER:11
THE GREATEST OF ALL THE THREE NUMBERS IS: 11.0

STRING COMPARISON

ENTER THE STRING:nameless
YES

TRIANGLE VALIDITY CHECKER

ENTER THE LENGTH OF FIRST SIDE:14
ENTER THE LENGTH OF SECOND SIDE:22
ENTER THE LENGTH OF THE THIRD SIDE:23
NO,TRIANGLE CANNOT BE FORMED

